In [1]:
%load_ext autoreload
%autoreload 2

# Dataset split K-means cross validation

In [2]:
import numpy as np

## Load paths

In [3]:
import glob
import os

root = os.path.join('datasets', 'volcanic_eruptions')

eruption_paths = glob.glob(os.path.join(os.path.join(root, 'eruption'),'*'))
no_eruption_paths = glob.glob(os.path.join(os.path.join(root, 'no_eruption'),'*'))

In [4]:
paths = np.concatenate((eruption_paths, no_eruption_paths))

In [5]:
K = 5

In [6]:
import random
def split(paths, K):
    random.shuffle(paths)
    
    len_k = int(len(paths)//K)
    print(len(paths), len_k)
    
    datasets = []
    
    for i in range(K):
        datasets.append([paths[i*len_k:(i+1)*len_k]])
    
    return datasets

In [7]:
datasets = split(paths, K)

1317 263


## Create CNN model

In [8]:
from cnnModel import cnnModel

In [11]:
for k in range(K):
    
    train_set = np.concatenate(np.concatenate(np.delete(np.array(datasets), 0, axis = 0)))
    val_set =  datasets[k][0]
    
    model = cnnModel('{}-fold-cross-validation'.format(k), train_set,val_set)
    print(' -----------------  Fold {}  -----------------'.format(k))
    _ = model.train(epochs = 100, batch_size = 16)
    ground_truths, predictions, confusion_matrix, norm_confusion_matrix = model.test()
    
    print(confusion_matrix)
    print(norm_confusion_matrix)

 -----------------  Fold 0  -----------------
Epoch 1/100
65/65 [==============================] - 21s 281ms/step - loss: 0.5431 - accuracy: 0.7192 - val_loss: 0.6434 - val_accuracy: 0.6797
Epoch 2/100
65/65 [==============================] - 18s 284ms/step - loss: 0.4973 - accuracy: 0.7577 - val_loss: 0.7115 - val_accuracy: 0.6719
Epoch 3/100
65/65 [==============================] - 18s 279ms/step - loss: 0.4940 - accuracy: 0.7471 - val_loss: 0.7522 - val_accuracy: 0.6992
Epoch 4/100
65/65 [==============================] - 18s 277ms/step - loss: 0.4561 - accuracy: 0.7865 - val_loss: 0.7185 - val_accuracy: 0.6836
Epoch 5/100
65/65 [==============================] - 18s 277ms/step - loss: 0.4401 - accuracy: 0.8029 - val_loss: 0.5849 - val_accuracy: 0.6836
Epoch 6/100
65/65 [==============================] - 18s 280ms/step - loss: 0.4238 - accuracy: 0.7875 - val_loss: 0.5911 - val_accuracy: 0.7109
Epoch 7/100
65/65 [==============================] - 18s 278ms/step - loss: 0.4205 - accur

100%|████████████████████████████████████████████████████████████████████████████████| 263/263 [00:11<00:00, 22.96it/s]
C:\Users\aless\anaconda3\envs\tf\lib\site-packages\keras\optimizer_v2\rmsprop.py:130: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)


[[171  11]
 [ 22  59]]
[[0.93956044 0.06043956]
 [0.27160494 0.72839506]]
 -----------------  Fold 1  -----------------
Epoch 1/100
65/65 [==============================] - 18s 277ms/step - loss: 0.5767 - accuracy: 0.6856 - val_loss: 0.6436 - val_accuracy: 0.6484
Epoch 2/100
65/65 [==============================] - 18s 281ms/step - loss: 0.5081 - accuracy: 0.7240 - val_loss: 0.6389 - val_accuracy: 0.6484
Epoch 3/100
65/65 [==============================] - 17s 271ms/step - loss: 0.4707 - accuracy: 0.7635 - val_loss: 0.7095 - val_accuracy: 0.6328
Epoch 4/100
65/65 [==============================] - 18s 278ms/step - loss: 0.4740 - accuracy: 0.7606 - val_loss: 0.7106 - val_accuracy: 0.6445
Epoch 5/100
65/65 [==============================] - 18s 274ms/step - loss: 0.4554 - accuracy: 0.7731 - val_loss: 0.7198 - val_accuracy: 0.6328
Epoch 6/100
65/65 [==============================] - 17s 272ms/step - loss: 0.4440 - accuracy: 0.7923 - val_loss: 0.5865 - val_accuracy: 0.7266
Epoch 7/100
65/6

100%|████████████████████████████████████████████████████████████████████████████████| 263/263 [00:11<00:00, 22.50it/s]
C:\Users\aless\anaconda3\envs\tf\lib\site-packages\keras\optimizer_v2\rmsprop.py:130: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)


[[155  15]
 [ 13  80]]
[[0.91176471 0.08823529]
 [0.13978495 0.86021505]]
 -----------------  Fold 2  -----------------
Epoch 1/100
65/65 [==============================] - 20s 303ms/step - loss: 0.5264 - accuracy: 0.7212 - val_loss: 0.6096 - val_accuracy: 0.7227
Epoch 2/100
65/65 [==============================] - 20s 308ms/step - loss: 0.4682 - accuracy: 0.7558 - val_loss: 0.6046 - val_accuracy: 0.7227
Epoch 3/100
65/65 [==============================] - 19s 299ms/step - loss: 0.4698 - accuracy: 0.7721 - val_loss: 0.7465 - val_accuracy: 0.7188
Epoch 4/100
65/65 [==============================] - 19s 293ms/step - loss: 0.4712 - accuracy: 0.7635 - val_loss: 0.8736 - val_accuracy: 0.7383
Epoch 5/100
65/65 [==============================] - 19s 290ms/step - loss: 0.4310 - accuracy: 0.7769 - val_loss: 1.0344 - val_accuracy: 0.7188
Epoch 6/100
65/65 [==============================] - 20s 311ms/step - loss: 0.3850 - accuracy: 0.8077 - val_loss: 1.0817 - val_accuracy: 0.6953
Epoch 7/100
65/6

100%|████████████████████████████████████████████████████████████████████████████████| 263/263 [00:12<00:00, 20.42it/s]
C:\Users\aless\anaconda3\envs\tf\lib\site-packages\keras\optimizer_v2\rmsprop.py:130: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)


[[172  18]
 [ 10  63]]
[[0.90526316 0.09473684]
 [0.1369863  0.8630137 ]]
 -----------------  Fold 3  -----------------
Epoch 1/100
65/65 [==============================] - 22s 325ms/step - loss: 0.5353 - accuracy: 0.6981 - val_loss: 0.6287 - val_accuracy: 0.7227
Epoch 2/100
65/65 [==============================] - 21s 326ms/step - loss: 0.4939 - accuracy: 0.7365 - val_loss: 0.5506 - val_accuracy: 0.7500
Epoch 3/100
65/65 [==============================] - 21s 323ms/step - loss: 0.4565 - accuracy: 0.7760 - val_loss: 0.5553 - val_accuracy: 0.7422
Epoch 4/100
65/65 [==============================] - 21s 320ms/step - loss: 0.4543 - accuracy: 0.7721 - val_loss: 0.6381 - val_accuracy: 0.7148
Epoch 5/100
65/65 [==============================] - 21s 325ms/step - loss: 0.4425 - accuracy: 0.8010 - val_loss: 0.6566 - val_accuracy: 0.6992
Epoch 6/100
65/65 [==============================] - 20s 319ms/step - loss: 0.4383 - accuracy: 0.7846 - val_loss: 0.4924 - val_accuracy: 0.7500
Epoch 7/100
65/6

100%|████████████████████████████████████████████████████████████████████████████████| 263/263 [00:11<00:00, 21.95it/s]
C:\Users\aless\anaconda3\envs\tf\lib\site-packages\keras\optimizer_v2\rmsprop.py:130: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)


[[170  20]
 [  9  64]]
[[0.89473684 0.10526316]
 [0.12328767 0.87671233]]
 -----------------  Fold 4  -----------------
Epoch 1/100
65/65 [==============================] - 21s 314ms/step - loss: 0.5713 - accuracy: 0.6606 - val_loss: 0.6259 - val_accuracy: 0.6680
Epoch 2/100
65/65 [==============================] - 20s 315ms/step - loss: 0.4925 - accuracy: 0.7394 - val_loss: 0.6282 - val_accuracy: 0.6914
Epoch 3/100
65/65 [==============================] - 20s 313ms/step - loss: 0.4599 - accuracy: 0.7577 - val_loss: 0.5824 - val_accuracy: 0.6914
Epoch 4/100
65/65 [==============================] - 20s 312ms/step - loss: 0.4591 - accuracy: 0.7654 - val_loss: 0.7008 - val_accuracy: 0.6484
Epoch 5/100
65/65 [==============================] - 20s 314ms/step - loss: 0.4588 - accuracy: 0.7750 - val_loss: 0.6501 - val_accuracy: 0.6758
Epoch 6/100
65/65 [==============================] - 20s 314ms/step - loss: 0.4451 - accuracy: 0.7952 - val_loss: 0.4780 - val_accuracy: 0.7422
Epoch 7/100
65/6

100%|████████████████████████████████████████████████████████████████████████████████| 263/263 [00:11<00:00, 22.07it/s]

[[165  12]
 [ 17  69]]
[[0.93220339 0.06779661]
 [0.19767442 0.80232558]]
